import test from 'node:test';
import assert from 'node:assert/strict';
import {walletSheet,walletRequest,walletContact,decimal} from '../public/godaddy-express-contract.js';
import {setupExpress} from '../public/godaddy-express.js';
const quote=(o={})=>({sessionId:'gd_'+'a'.repeat(32),businessId:'merchant',applicationId:'application',country:'US',countries:['US','CA','FR'],paymentsEnabled:true,currency:'USD',chargeCurrency:'CAD',chargeMinor:14894,total:10797,shipping:0,tax:0,items:[{title:'Collagen',quantity:1,lineTotalMinor:3199},{title:'Yeast',quantity:1,lineTotalMinor:3199},{title:'Probiotic',quantity:1,lineTotalMinor:4399},{title:'Gift',quantity:1,lineTotalMinor:0}],...o});
const address=(o={})=>({name:'Alex Example',emailAddress:'alex@example.test',addressLines:['12 Example Street','Unit 3'],locality:'Albany',administrativeArea:'NY',postalCode:'12207',countryCode:'US',...o});
const event=(o={})=>({source:'google_pay',nonce:'synthetic-wallet-nonce',shippingAddress:address(),billingAddress:address(),...o});
const cfg={applePay:true,googlePay:true,merchantCountry:'CA',currency:'CAD'};
const cents=s=>Number(s.replace('.',''));
test('wallet total is exact server CAD total, not displayed USD total',()=>{const q=quote(),s=walletSheet(q);assert.equal(s.total.amount,'148.94');assert.equal(s.lineItems.reduce((n,i)=>n+cents(i.amount),0),14894);assert.equal(s.lineItems[3].amount,'0.00');assert.equal(q.total,10797);});
test('shipping, tax and cumulative rounding reconcile to the cent',()=>{for(let i=1;i<200;i++){const q=quote({total:3+i,chargeMinor:6+i,shipping:1,tax:i,items:[{title:'Two cents',quantity:1,lineTotalMinor:2}]});const s=walletSheet(q);assert.equal(s.lineItems.reduce((n,r)=>n+cents(r.amount),0),q.chargeMinor);}});
for(const o of [{chargeCurrency:'USD'},{chargeMinor:0},{chargeMinor:12.5},{total:0},{shipping:-1},{total:10796},{items:[{title:'bad',lineTotalMinor:NaN}]}])test('invalid quote rejected '+JSON.stringify(o),()=>assert.throws(()=>walletSheet(quote(o))));
test('decimal preserves cents',()=>{assert.equal(decimal(1),'0.01');assert.equal(decimal(100),'1.00');assert.equal(decimal(14894),'148.94');assert.throws(()=>decimal(-1));});
test('email and shipping requested by wallet before form entry',()=>{const r=walletRequest(quote(),cfg,{});assert.equal(r.requireEmail,true);assert.equal(r.requireShippingAddress,true);assert.equal(r.country,'CA');assert.equal(r.currency,'CAD');assert.equal(r.disableWallets.paze,true);});
test('contact mapped without payment token in person object',()=>{const c=walletContact(event(),quote());assert.equal(c.email,'alex@example.test');assert.equal(c.shipping.first_name,'Alex');assert.equal(c.shipping.last_name,'Example');assert.equal(c.confirmedChargeMinor,14894);assert.equal('nonce' in c,false);});
for(const o of [{source:'paze'},{nonce:''},{shippingAddress:address({countryCode:'CA'})},{shippingAddress:address({emailAddress:''}),billingAddress:address({emailAddress:''})},{billingAddress:null},{shippingAddress:address({postalCode:''})}])test('invalid wallet input rejected '+JSON.stringify(o),()=>assert.throws(()=>walletContact(event(o),quote())));
class Node {constructor(){this.children=[];this.dataset={};this.hidden=true;this.attrs={};}append(n){this.children.push(n);}setAttribute(k,v){this.attrs[k]=v;}querySelector(){return this.container;}}
async function harness({supported={applePay:true,googlePay:true},api:apiOverride}={}){
 const original={fetch:globalThis.fetch,window:globalThis.window,document:globalThis.document};
 const box=new Node();box.container=new Node();const calls=[],completed=[],active=[];let q=quote(),sdk,paid=null,pending=0;
 class FakeSDK {constructor(b,a,r){this.initial=r;this.listeners={};sdk=this;}on(k,f){this.listeners[k]=f;}async supportWalletPayments(){return supported;}mount(id,doc,opts){this.opts=opts;}startApplePaySession(s){this.sheet=s;}startGooglePaySession(s){this.sheet=s;}}
 globalThis.window={TokenizeJs:FakeSDK};globalThis.document={documentElement:{lang:'en'},head:new Node(),createElement:()=>new Node()};globalThis.fetch=async()=>({ok:true,json:async()=>cfg});
 const controller=await setupExpress({box,getQuote:()=>q,getLabels:()=>({failed:'Failed',checking:'Checking',shipping:'Delivery',tax:'Taxes'}),canStart:()=>true,setActive:v=>active.push(v),acceptQuote:v=>{q=v;},api:async body=>{calls.push(body);if(apiOverride)return apiOverride(body,q);if(body.action==='prepare')return {preparedId:'synthetic-prepared'};if(body.action==='pay')return {paid:true,orderId:'synthetic-order'};throw Error('unexpected');},onContact:()=>{},onPaid:r=>{paid=r;},onPending:async()=>{pending++;},onError:()=>{}});
 return {box,controller,calls,completed,active,sdk,get paid(){return paid;},get pending(){return pending;},get q(){return q;},setQ:n=>{q=n;},start:(source='google_pay')=>sdk.opts.buttonOptions.onClick({source}),authorize:o=>sdk.listeners.payment_authorized(event({...o,complete:r=>completed.push(r)})),close:()=>sdk.listeners.close_wallet(),shipping:country=>new Promise(resolve=>sdk.listeners.shipping_address_change({shippingAddress:{countryCode:country},updateWith:resolve})),restore:()=>{for(const k in original){if(original[k]===undefined)delete globalThis[k];else globalThis[k]=original[k];}}};
}
for(const method of ['apple_pay','google_pay'])test(method+' uses existing prepare then pay, and completes only after paid',async()=>{const h=await harness();try{h.start(method);assert.equal(h.calls.length,0);assert.equal(h.sdk.sheet.total.amount,'148.94');await h.authorize({source:method});assert.deepEqual(h.calls.map(c=>c.action),['prepare','pay']);assert.equal(h.completed.length,1);assert.equal(h.completed[0],undefined);assert.equal(h.paid.paid,true);}finally{h.restore();}});
test('cancel before authorization creates no financial request',async()=>{const h=await harness();try{h.start();h.close();assert.equal(h.calls.length,0);assert.equal(h.active.at(-1),false);}finally{h.restore();}});
test('duplicate wallet authorization never duplicates payment',async()=>{let finish;const h=await harness({api:async b=>b.action==='prepare'?new Promise(r=>{finish=r;}):{paid:true}});try{h.start();const first=h.authorize();await Promise.resolve();await Promise.resolve();await h.authorize();finish({preparedId:'x'});await first;assert.equal(h.calls.filter(c=>c.action==='pay').length,1);}finally{h.restore();}});
test('prepare failure never submits nonce',async()=>{const h=await harness({api:async()=>{throw Error('prepare rejected');}});try{h.start();await h.authorize();assert.deepEqual(h.calls.map(c=>c.action),['prepare']);assert.ok(h.completed[0].error);assert.equal(h.paid,null);}finally{h.restore();}});
test('lost payment response locks checkout, invokes status polling only once',async()=>{const h=await harness({api:async b=>{if(b.action==='prepare')return {preparedId:'x'};throw Error('timeout');}});try{h.start();await h.authorize();h.close();h.start();await h.authorize();assert.equal(h.calls.filter(c=>c.action==='pay').length,1);assert.equal(h.pending,1);assert.equal(h.paid,null);}finally{h.restore();}});
test('shipping country updates only from a server response before authorization',async()=>{const h=await harness({api:async (b,q)=>b.action==='change-country'?{...q,sessionId:'gd_'+'b'.repeat(32),country:'CA',currency:'CAD',total:14894,items:[{title:'Cart',quantity:4,lineTotalMinor:14894}]}:b.action==='prepare'?{preparedId:'x'}:{paid:true}});try{h.start();const update=await h.shipping('CA');assert.equal(update.total.amount,'148.94');await h.authorize({shippingAddress:address({countryCode:'CA'})});assert.deepEqual(h.calls.map(c=>c.action),['change-country','prepare','pay']);assert.equal(h.calls[1].shipping.country,'CA');}finally{h.restore();}});
test('unexpected client country or changed server quote prevents payment',async()=>{const h=await harness();try{h.start();h.setQ(quote({chargeMinor:9999}));await h.authorize();assert.equal(h.calls.length,0);assert.ok(h.completed[0].error);}finally{h.restore();}});
test('unsupported methods not shown and normal checkout remains untouched',async()=>{const h=await harness({supported:{applePay:false,googlePay:false}});try{assert.equal(h.controller,null);assert.equal(h.box.hidden,true);assert.equal(h.calls.length,0);}finally{h.restore();}});
